label: ErrorableCheckbox
status: wip

context:
  componentSourcePath: './ErrorableCheckbox.jsx'
  id: default
  title: 'ErrorableCheckbox'
  content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id felis pulvinar ligula ultricies sollicitudin eget nec dui. Cras augue velit, pellentesque sit amet nisl ut, tristique suscipit sem. Cras sollicitudin auctor mattis.'
